from datetime import timedelta
import secrets

import requests
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.shortcuts import redirect
from django.utils import timezone
from rest_framework.permissions import AllowAny, IsAuthenticated

from accounts.permissions import IsMobileVerified
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import ZoomConnection


User = get_user_model()


class ZoomLoginView(APIView):
    permission_classes = [IsAuthenticated, IsMobileVerified]

    def get(self, request):
        authorization_url = "https://zoom.us//oauth/authorize"

        # Use a short URL-safe state value because Zoom rejects
        # Django's longer signed state format for this development app.
        state = secrets.token_hex(24)

        # Store the MeetGate user association server-side for 10 minutes.
        cache.set(
            f"zoom_oauth_state:{state}",
            request.user.id,
            timeout=600,
        )

        # Match the authorization URL format generated by Zoom Platform Studio.
        authorization_url = (
            f"{authorization_url}"
            f"?response_type=code"
            f"&client_id={settings.ZOOM_CLIENT_ID}"
            f"&redirect_uri={settings.ZOOM_REDIRECT_URI}"
            f"&state={state}"
        )

        return Response(
    {
        "authorization_url": authorization_url,
        "client_id_loaded": settings.ZOOM_CLIENT_ID,
        "redirect_uri_loaded": settings.ZOOM_REDIRECT_URI,
    }
)



class ZoomCallbackView(APIView):
    permission_classes = [AllowAny]

    def get(self, request):
        authorization_code = request.query_params.get("code")
        state = request.query_params.get("state")
        zoom_error = request.query_params.get("error")

        if zoom_error:
            return redirect(
                "http://localhost:5173/dashboard?zoom=denied"
            )

        if not authorization_code or not state:
            return redirect(
                "http://localhost:5173/dashboard?zoom=failed"
            )

        # Resolve and consume the short-lived state token.
        user_id = cache.get(
            f"zoom_oauth_state:{state}"
        )

        if user_id is None:
            return redirect(
                "http://localhost:5173/dashboard?zoom=invalid-state"
            )

        cache.delete(
            f"zoom_oauth_state:{state}"
        )

        try:
            user = User.objects.get(
                id=user_id
            )
        except User.DoesNotExist:
            return redirect(
                "http://localhost:5173/dashboard?zoom=invalid-state"
            )

        token_response = requests.post(
            "https://zoom.us/oauth/token",
            params={
                "grant_type": "authorization_code",
                "code": authorization_code,
                "redirect_uri": settings.ZOOM_REDIRECT_URI,
            },
            auth=(
                settings.ZOOM_CLIENT_ID,
                settings.ZOOM_CLIENT_SECRET,
            ),
            timeout=20,
        )

        if not token_response.ok:
            return redirect(
                "http://localhost:5173/dashboard?zoom=token-error"
            )

        token_data = token_response.json()

        access_token = token_data.get("access_token")
        refresh_token = token_data.get("refresh_token")
        expires_in = token_data.get("expires_in", 3600)
        scopes = token_data.get("scope", "")

        if not access_token or not refresh_token:
            return redirect(
                "http://localhost:5173/dashboard?zoom=token-error"
            )

        # Fetch the connected Zoom user's profile when the granted
        # user:read:user scope permits access to /users/me.
        profile_response = requests.get(
            "https://api.zoom.us/v2/users/me",
            headers={
                "Authorization": f"Bearer {access_token}",
            },
            timeout=20,
        )

        zoom_user_id = ""
        zoom_email = ""

        if profile_response.ok:
            profile_data = profile_response.json()
            zoom_user_id = str(profile_data.get("id", ""))
            zoom_email = profile_data.get("email", "")

        ZoomConnection.objects.update_or_create(
            user=user,
            defaults={
                "zoom_user_id": zoom_user_id,
                "zoom_email": zoom_email,
                "access_token": access_token,
                "refresh_token": refresh_token,
                "token_expires_at": (
                    timezone.now()
                    + timedelta(seconds=expires_in)
                ),
                "scopes": scopes,
            },
        )

        return redirect(
            "http://localhost:5173/dashboard?zoom=connected"
        )


class ZoomConnectionStatusView(APIView):
    permission_classes = [IsAuthenticated, IsMobileVerified]

    def get(self, request):
        connection = ZoomConnection.objects.filter(
            user=request.user
        ).first()

        return Response(
            {
                "connected": connection is not None,
                "zoom_email": (
                    connection.zoom_email
                    if connection
                    else ""
                ),
            }
        )
