# Generated by Django 6.0.6 on 2026-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountprofile_mobile_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
