# Generated by Django 6.0.6 on 2026-08-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='join_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
